In [2]:
import numpy as np

In [3]:
a= np.array([1,2,3], dtype='int32');

In [4]:
print(a);

[1 2 3]


In [7]:
a.dtype

dtype('int32')

In [11]:
b=np.array([[1,2,3],[2,3,4]]);
print(b);

[[1 2 3]
 [2 3 4]]


In [8]:
#get dimension
a.ndim

1

In [9]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
#get type
a.dtype

dtype('int32')

In [14]:
a.size

3

In [15]:
a.itemsize

4

In [16]:
#access and chnage

In [17]:
 a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [15]:
a[1,5]

np.int64(13)

In [16]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
a[:,3]

array([ 4, 11])

#### Acesseing and changind elemnts in an array

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
a[1,5]

np.int64(13)

In [20]:
#get a specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#get a specific column
a[:,4]

array([ 5, 12])

In [22]:
a[0,:-1:2]

array([1, 3, 5])

In [23]:
a[1,5]=20
a[:,2]=[1,2]

In [24]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

###### 3d matrix example

In [25]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
b[0,1,1]

np.int64(4)

In [27]:
#different type of array

In [30]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.full((2,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [33]:
np.random.rand(4,2)

array([[0.32061116, 0.40237377],
       [0.82094342, 0.70814871],
       [0.61902904, 0.45456753],
       [0.69276194, 0.76409765]])

In [35]:
np.random.randint(-100,4,size=(2,4))

array([[-87, -22, -97, -86],
       [-69, -65, -20, -54]], dtype=int32)

In [38]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
#repeat an array
arr=np.array([[1,2,3]])

In [56]:
r1=np.repeat(arr,3,axis=0)

In [57]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [58]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9

output[1:-1,1:-1]=z
output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
#copying an array
a=np.array([1,2,3])
b=a
b[1]=100 #changes value of a
a

array([  1, 100,   3])

In [61]:
a=np.array([1,2,3])
b=a.copy()
b[1]=100 # value of a remains same as the meory location of the copy created is different
a

array([1, 2, 3])

#### Mathematics

In [62]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [63]:
a+2

array([3, 4, 5, 6])

In [64]:
a-2

array([-1,  0,  1,  2])

In [65]:
a*2

array([2, 4, 6, 8])

In [66]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [67]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [68]:
a**2

array([ 1,  4,  9, 16])

In [69]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [70]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b) #product of the matrix

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [71]:
# find the dterminant
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

#### Statistics

In [72]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.min(stats)

np.int64(1)

In [74]:
np.max(stats)

np.int64(6)

In [75]:
np.sum(stats)

np.int64(21)

#### reorganizing array

In [78]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((4,2))  #before.reshape((2,3)) # will not work as 2*3=6 and not 8(elemts in before)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [79]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
np.vstack([v1,v1,v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
h1 = np.ones((2,4))
h2 = np.zeros((2,8))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])